# Generated by Django 5.0 on 2023-12-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scube_ss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True)),
                ('Catogory', models.CharField(choices=[('CUPBOARD', 'CUPBOARD'), ('TABLE', 'TABLE'), ('BED-BEDSIDE', 'BED-BEDSIDE'), ('POOJA-STAND', 'POOJA-STAND'), ('TV-STAND', 'TV-STAND'), ('SOFA', 'SOFA'), ('OTHERS', 'OTHERS'), ('ORDER', 'ORDER')], max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('size', models.CharField(blank=True, null=True)),
                ('prize', models.IntegerField(blank=True, null=True)),
                ('material', models.CharField(null=True)),
                ('color', models.CharField(blank=True, null=True)),
                ('pr_date', models.DateField(null=True)),
                ('sl_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCUBE', 'SCUBE'), ('GODOWN', 'GODOWN'), ('SALE', 'SALE'), ('ORDER', 'ORDER')], max_length=50, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
