# Generated by Django 5.0 on 2023-12-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, null=True)),
                ('color', models.CharField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('details', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='scube_ss',
            name='Catogory',
            field=models.CharField(choices=[('CUPBOARD', 'CUPBOARD'), ('TABLE', 'TABLE'), ('BEDROOM-SET', 'BEDROOM-SET'), ('POOJA-STAND', 'POOJA-STAND'), ('TV-STAND', 'TV-STAND'), ('SOFA', 'SOFA'), ('OTHERS', 'OTHERS'), ('ORDER', 'ORDER')], max_length=50, null=True),
        ),
    ]
